USE [master]
GO
/****** Object:  Database [Malaria_DB]    Script Date: 2019/05/01 17:20:19 ******/
CREATE DATABASE [Malaria_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Malaria_DB', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Malaria_DB.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Malaria_DB_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Malaria_DB_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Malaria_DB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Malaria_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Malaria_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Malaria_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Malaria_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Malaria_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Malaria_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [Malaria_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Malaria_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Malaria_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Malaria_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Malaria_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Malaria_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Malaria_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Malaria_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Malaria_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Malaria_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Malaria_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Malaria_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Malaria_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Malaria_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Malaria_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Malaria_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Malaria_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Malaria_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [Malaria_DB] SET  MULTI_USER 
GO
ALTER DATABASE [Malaria_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Malaria_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Malaria_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Malaria_DB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Malaria_DB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Malaria_DB', N'ON'
GO
USE [Malaria_DB]
GO
/****** Object:  Table [dbo].[Causes]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Causes](
	[Cause_ID] [int] IDENTITY(1,1) NOT NULL,
	[Cause_Desc] [text] NOT NULL,
	[Des_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Cause_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Desease]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Desease](
	[Des_ID] [int] IDENTITY(1,1) NOT NULL,
	[Des_Desc] [text] NOT NULL,
	[Des_Name] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Des_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Loc_Des]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Loc_Des](
	[Des_ID] [int] NULL,
	[Loc_ID] [int] NULL,
	[Loc_Des_ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Loc_Des] PRIMARY KEY CLUSTERED 
(
	[Loc_Des_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Location]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Location](
	[Loc_ID] [int] IDENTITY(1,1) NOT NULL,
	[Loc_Severity] [nvarchar](500) NOT NULL,
	[Loc_Name] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Loc_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Medical_Proffesionals]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Medical_Proffesionals](
	[MP_ID] [int] IDENTITY(1,1) NOT NULL,
	[MP_Name] [nvarchar](50) NOT NULL,
	[MP_Surname] [nvarchar](50) NOT NULL,
	[MP_Email] [nvarchar](50) NOT NULL,
	[MP_Password] [varchar](20) NOT NULL,
	[GUID] [uniqueidentifier] NULL,
	[GUIDExp] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[MP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Notifications]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Notifications](
	[Note_ID] [int] IDENTITY(1,1) NOT NULL,
	[Note_Desc] [text] NOT NULL,
	[Note_Date] [nvarchar](20) NOT NULL,
	[MP_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Note_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Prevention]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Prevention](
	[Prev_ID] [int] IDENTITY(1,1) NOT NULL,
	[Prev_Desc] [text] NOT NULL,
	[Prev_Type] [nvarchar](50) NOT NULL,
	[Des_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Prev_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Risk_Period]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Risk_Period](
	[RiskP_ID] [int] IDENTITY(1,1) NOT NULL,
	[RiskP_Desc] [text] NOT NULL,
	[RiskP_Type] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RiskP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RP_Des]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RP_Des](
	[Des_ID] [int] NULL,
	[RiskP_ID] [int] NULL,
	[RP_Des_ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_RP_Des] PRIMARY KEY CLUSTERED 
(
	[RP_Des_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Symp_Des]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Symp_Des](
	[Des_ID] [int] NULL,
	[Symp_ID] [int] NULL,
	[Symp_Des_ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Symp_Des] PRIMARY KEY CLUSTERED 
(
	[Symp_Des_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Symptoms]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Symptoms](
	[Symp_ID] [int] IDENTITY(1,1) NOT NULL,
	[Symp_Desc] [text] NOT NULL,
	[Symp_Type] [nvarchar](50) NOT NULL,
	[Symp_Duration] [nvarchar](300) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Symp_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Treatment]    Script Date: 2019/05/01 17:20:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Treatment](
	[Treat_ID] [int] IDENTITY(1,1) NOT NULL,
	[Treat_Desc] [text] NOT NULL,
	[Treat_Type] [nvarchar](50) NOT NULL,
	[Des_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Treat_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE [dbo].[Causes]  WITH CHECK ADD FOREIGN KEY([Des_ID])
REFERENCES [dbo].[Desease] ([Des_ID])
GO
ALTER TABLE [dbo].[Loc_Des]  WITH CHECK ADD FOREIGN KEY([Des_ID])
REFERENCES [dbo].[Desease] ([Des_ID])
GO
ALTER TABLE [dbo].[Loc_Des]  WITH CHECK ADD FOREIGN KEY([Loc_ID])
REFERENCES [dbo].[Location] ([Loc_ID])
GO
ALTER TABLE [dbo].[Notifications]  WITH CHECK ADD FOREIGN KEY([MP_ID])
REFERENCES [dbo].[Medical_Proffesionals] ([MP_ID])
GO
ALTER TABLE [dbo].[Prevention]  WITH CHECK ADD FOREIGN KEY([Des_ID])
REFERENCES [dbo].[Desease] ([Des_ID])
GO
ALTER TABLE [dbo].[RP_Des]  WITH CHECK ADD FOREIGN KEY([Des_ID])
REFERENCES [dbo].[Desease] ([Des_ID])
GO
ALTER TABLE [dbo].[RP_Des]  WITH CHECK ADD FOREIGN KEY([RiskP_ID])
REFERENCES [dbo].[Risk_Period] ([RiskP_ID])
GO
ALTER TABLE [dbo].[Symp_Des]  WITH CHECK ADD FOREIGN KEY([Des_ID])
REFERENCES [dbo].[Desease] ([Des_ID])
GO
ALTER TABLE [dbo].[Symp_Des]  WITH CHECK ADD FOREIGN KEY([Symp_ID])
REFERENCES [dbo].[Symptoms] ([Symp_ID])
GO
ALTER TABLE [dbo].[Treatment]  WITH CHECK ADD FOREIGN KEY([Des_ID])
REFERENCES [dbo].[Desease] ([Des_ID])
GO
USE [master]
GO
ALTER DATABASE [Malaria_DB] SET  READ_WRITE 
GO
