//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalariaAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_Des
    {
        public Nullable<int> Des_ID { get; set; }
        public Nullable<int> RiskP_ID { get; set; }
        public int RP_Des_ID { get; set; }
    
        public virtual Desease Desease { get; set; }
        public virtual Risk_Period Risk_Period { get; set; }
    }
}
