//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalariaAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MalariaDBEntities1 : DbContext
    {
        public MalariaDBEntities1()
            : base("name=MalariaDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caus> Causes { get; set; }
        public virtual DbSet<Desease> Deseases { get; set; }
        public virtual DbSet<Loc_Des> Loc_Des { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Medical_Proffesionals> Medical_Proffesionals { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Prevention> Preventions { get; set; }
        public virtual DbSet<Risk_Period> Risk_Period { get; set; }
        public virtual DbSet<RP_Des> RP_Des { get; set; }
        public virtual DbSet<Symp_Des> Symp_Des { get; set; }
        public virtual DbSet<Symptom> Symptoms { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
    }
}
