//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalariaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Note_ID { get; set; }
        public string Note_Desc { get; set; }
        public string Note_Date { get; set; }
        public Nullable<int> MP_ID { get; set; }
    
        public virtual Medical_Proffesionals Medical_Proffesionals { get; set; }
    }
}
